<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*Ce cahier contient un extrait de [Programmation Python et méthodes numériques - Un guide pour les ingénieurs et les scientifiques](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html), le contenu est également disponible sur [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*Les droits d'auteur du livre appartiennent à Elsevier. Nous avons également ce livre interactif en ligne pour une meilleure expérience d'apprentissage. Le code est publié sous la [licence MIT](https://opensource.org/licenses/MIT). Si vous trouvez ce contenu utile, pensez à soutenir le travail sur [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) ou [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1) !*

<!--NAVIGATION-->
< [6.2 Divide and Conquer](chapter06.02-Divide-and-Conquer.ipynb) | [Contents](Index.ipynb) | [7.0 Objects and Classes](chapter07.00-Objects-and-Classes.ipynb) >

# Résumé


1. Une fonction récursive est une fonction qui s'appelle elle-même.
2. Les fonctions récursives sont utiles lorsque les problèmes ont une structure hiérarchique plutôt qu'itérative.
3. Diviser pour mieux régner est une stratégie puissante de résolution de problèmes qui peut être utilisée pour résoudre des problèmes difficiles.

# Problèmes

1. Écrivez une fonction *my_sum(lst)* où *lst* est une liste et la sortie est la somme de tous les éléments de *lst*. Vous pouvez utiliser la récursivité ou l'itération pour résoudre le problème, mais n'utilisez pas la fonction *sum* de Python.

In [ ]:
def my_sum(lst):
    # Write your function code here
    
    return out

In [ ]:
# Output: 6
my_sum([1, 2, 3])

In [ ]:
# Output: 5050
my_sum(range(1,101))

2. Les polynômes de Chebyshev sont définis de manière récursive. Les polynômes de Chebyshev sont divisés en deux types : premier et deuxième. Les polynômes de Chebyshev du premier type, $T_n(x)$, et du deuxième type, $U_n(x)$, sont définis par les relations de récurrence suivantes :

\begin{equation}
T_n(x) = \begin{cases}
    1 & \text{if $n=0$}\\
    x & \text{if $n=1$}\\
    2xT_{n-1}(x)-T_{n-2}(x) & \text{otherwise}\\
    \end{cases}
\end{equation}

 \begin{equation}
U_n(x) = \begin{cases}
    1 & \text{if $n=0$}\\
    2x & \text{if $n=1$}\\
    2xU_{n-1}(x)-U_{n-2}(x) & \text{otherwise}\\
    \end{cases}
\end{equation}

 Écrivez une fonction *my_chebyshev_poly1(n,x)*, où la sortie *y* est le n-ième polynôme de Chebyshev du premier type évalué à *x*. Assurez-vous que votre fonction peut accepter des entrées de liste pour *x*. Vous pouvez supposer que *x* est une liste. La variable de sortie, *y*, doit également être une liste.

In [ ]:
def my_chebyshev_poly1(n,x):
    # Write your function code here
    
    return y

In [ ]:
x = [1, 2, 3, 4, 5]

In [ ]:
# Output: [1, 1, 1, 1, 1]
my_chebyshev_poly1(0,x)

In [ ]:
# Output: [1, 2, 3, 4, 5]
my_chebyshev_poly1(1,x)

In [ ]:
# Output: [1, 26, 99, 244, 485]
my_chebyshev_poly1(3,x)

3. La fonction Ackermann, *A*, est une fonction à croissance rapide définie par la relation récursive :

 \begin{equation}
A(m, n) = \begin{cases}
    n+1 &\text{if $m=0$}\\
    A(m-1,1) &\text{if  $m>0$ and $n=1$}\\
    A(m-1,A(m,n-1)) & \text{if  $m>0$ and $n>0$}\\
    \end{cases}
\end{equation}

 Écrivez une fonction *my_ackermann(m,n)*, où la sortie est la fonction Ackermann calculée pour *m* et *n*.
    
 *my_ackermann(4,4)* est si grand qu'il serait difficile de l'écrire. Bien que la fonction Ackermann n'ait pas de nombreuses utilisations pratiques, la fonction Ackermann inverse a plusieurs utilisations dans la planification des mouvements robotiques.

In [ ]:
def my_ackermann(m,n):
    # write your own function code here
    return out

In [ ]:
# Output: 3
my_ackermann(1,1)

In [ ]:
# Output: 4
my_ackermann(1,2)

In [ ]:
# Output: 9
my_ackermann(2,3)

In [ ]:
# Output: 61
my_ackermann(3,3)

In [ ]:
# Output: 125
my_ackermann(3,4)

4. Une fonction, *C(n,k)*, qui calcule le nombre de façons différentes de choisir de manière unique *k* objets parmi *n* sans répétition, est couramment utilisée dans de nombreuses applications statistiques. Par exemple, combien y a-t-il de coupes glacées à trois parfums s’il y a 10 parfums de glace ? Pour résoudre ce problème, nous devrions calculer *C(10,3)*, le nombre de façons de choisir trois saveurs de glace uniques parmi 10. La fonction *C* est communément appelée "<*>n*choisissez*k*." Vous pouvez supposer que*n*et*k*sont des nombres entiers.

 Si*n = k*, alors clairement*C(n,k) = 1*car il n'y a qu'un seul moyen de choisir*n*objets parmi*n*objets.

 Si*k = 1*, alors*C(n,k) = n*car choisir chacun des*n*objets est une manière de choisir un objet parmi*n*. Pour tous les autres cas,*C(n,k) = C(n-1,k) + C(n-1,k-1)*. Voyez-vous pourquoi ?

 Écrivez une fonction*my_n_choose_k(n,k)<*> qui calcule le nombre de fois où les objets $k$ peuvent être choisis de manière unique parmi les objets $n$ sans répétition.

In [ ]:
def my_n_choose_k(n,k):
    # Write your own function code here
    return out

In [ ]:
# Output: 10
my_n_choose_k(10,1)

In [ ]:
# Output: 1
my_n_choose_k(10,10)

In [ ]:
# Output: 120
my_n_choose_k(10,3)

5. Pour les achats payés en espèces, le vendeur doit restituer l'argent payé en trop. C'est ce qu'on appelle communément « donner de la monnaie ». Les billets et les pièces nécessaires pour rendre correctement la monnaie peuvent être définis par une relation récursive. Si le montant payé est supérieur à \undefined, soustrait du montant payé. Si le montant payé est supérieur à \undefined soustrait. Des clauses similaires peuvent être données pour chaque dénomination de la monnaie américaine. Les coupures de la monnaie américaine, en dollars, sont 100, 50, 20, 10, 5, 1, 0,25, 0,10, 0,05 et 0,01. Pour ce problème, nous ignorerons le billet de deux dollars, qui n’est pas en circulation courante. Vous pouvez supposer que le *coût* et
*payé* sont des scalaires, et ce *payé >= coût*. Le résultat
La variable, *change*, doit être une liste comme indiqué dans
le cas de test.

 Utilisez la récursivité pour programmer une fonction *my_change(cost,paid)* où *cost* est le coût de l'article, *paid* est le montant payé et le résultat <*>change<*> est une liste de billets et de pièces qui doivent être restitués au vendeur. Remarque : Attention au cas de base !

In [ ]:
def my_change(cost, paid):
    # Write your own function code here
    return change

In [ ]:
# Output: [50.0, 20.0, 1.0, 1.0, 0.25, 0.10, 0.05, 0.01, 0.01, 0.01]
my_change(27.57, 100)

6. Le nombre d'or, $\phi$, est la limite de $\frac{F(n+1)}{F(n)}$ lorsque *n* va vers l'infini et *F(n)* est le *n*-ième nombre de Fibonacci, qui peut être montré comme étant exactement $\frac{1 + \sqrt{5}}{2}$ et est d'environ 1,62. On dit que $G(n) = \frac{F(n+1)}{F(n)}$ est la *n*-ième approximation du nombre d'or, et $G(1) = 1$.

 On peut montrer que $\phi$ est aussi la limite de la fraction continue :
 
 $$\varphi = 1 + \dfrac{1}{1 + \dfrac{1}{1 + \dfrac{1}{1 + \ddots}}}.$$

 Écrivez une fonction récursive avec l'en-tête *my_golden_ratio(n)*, où la sortie est la *n*-ième approximation du nombre d'or selon la relation récursive de fraction continue. Vous devez utiliser l'approximation de fraction continue pour le nombre d'or, pas la définition $G(n) = F(n+1)/F(n)$. Cependant, pour les deux définitions, $G(1) = 1$.
 
 Des études ont montré que les rectangles dont le rapport hauteur/largeur (c'est-à-dire la longueur divisée par la largeur) est proche du nombre d'or sont plus agréables que les rectangles qui ne le sont pas. Quel est le rapport hauteur/largeur de nombreux écrans de télévision et de cinéma grand écran ?

In [ ]:
def my_golden_ratio(n):
    # Write your own function code here
    return out

In [ ]:
# Output: 1.618181818181818
my_golden_ratio(10)

In [ ]:
import numpy as np
(1 + np.sqrt(5))/2

7. Le plus grand commun diviseur de deux entiers *a* et *b* est le plus grand entier qui divise les deux nombres sans reste, et la fonction pour le calculer est notée *gcd(a ,b)*. La fonction *gcd* peut être écrite de manière récursive. Si *b* est égal à 0, alors *a* est le plus grand diviseur commun. Sinon, *gcd(a,b) = gcd(b,a%b)* où *a%b* est le reste de *a* divisé par *b*. Supposons que *a* et *b* soient des nombres entiers.

 Écrivez une fonction récursive *my_gcd(a,b)* qui calcule le plus grand diviseur commun de *a* et *b*. Supposons que *a* et *b* soient des nombres entiers.

In [ ]:
def my_gcd(a, b):
    # Write your own function code here
    return gcd

In [ ]:
# Output: 2
my_gcd(10, 4)

In [ ]:
# Output: 11
my_gcd(33, 121)

In [ ]:
# Output: 1
my_gcd(18, 1)

8. Le triangle de Pascal est un arrangement de nombres tel que chaque ligne est équivalente aux coefficients du développement binomial de $(x + y)^{(p-1)}$, où *p* est un entier positif supérieur ou égal à 1. Par exemple, $(x+y)^2 = 1 x^2 + 2 xy + 1 y^2$ donc le la troisième rangée du triangle de Pascal est 1 2 1.

 Soit $R_{m}$ représente la *m*-ème ligne du triangle de Pascal, et $R_m(n)$ soit le $n$-ème élément de la ligne. Par définition, $R_m$ a m éléments, et $R_m(1) = R_m(n) = 1$. Les éléments restants sont calculés par la relation récursive suivante : $R_m(i) = R_{m-1}(i-1) + R_{m-1}(i)$ pour $i = 2,\ldots,m-1$. Les premières lignes du triangle de Pascal sont représentées dans la figure suivante. Vous pouvez supposer que *m* est un entier strictement positif. La variable de sortie, *row*, doit être une liste.
 
 idhtml1
 
 Écrivez une fonction avec *my_pascal_row(m)* où la variable de sortie *row* est la *m*-ième ligne du triangle Pascal. Vous pouvez supposer que *m* est un entier strictement positif.

In [ ]:
def my_pascal_row(m):
    # Write your own function code here
    return row

In [ ]:
# Output: [1]
my_pascal_row(1)

In [ ]:
# Output: [1, 1]
my_pascal_row(2)

In [ ]:
# Output: [1, 2, 1]
my_pascal_row(3)

In [ ]:
# Output: [1, 3, 3, 1]
my_pascal_row(4)

In [ ]:
# Output: [1, 4, 6, 4, 1]
my_pascal_row(5)

9. Considérons une matrice $n\times{n}$ de la forme suivante :

 $$A =
\left[{\begin{array}{l@{\quad}l@{\quad}l@{\quad}l@{\quad}l}
1 & 1 & 1 & 1 & 1\\ 
1 & 0 & 0 & 0 & 0\\ 
1 & 0 & 1 & 1 & 0\\
1 & 0 & 0 & 1 & 0\\
1 & 1 & 1 & 1 & 0
\end{array}}\right]
$$

 où ceux-ci forment une spirale droite. Écrivez une fonction *my_spiral_ones(n)* qui produit une matrice $n\times{n}$ de la forme donnée. Assurez-vous que les étapes récursives sont dans le bon ordre (c'est-à-dire qu'elles vont à droite, puis en bas, puis à gauche, puis en haut, puis à droite, etc.).

In [ ]:
def my_spiral_ones(n):
    # Write your own function code here
    return A

In [ ]:
# Output: 1
my_spiral_ones(1)

In [ ]:
# Output: 
# array([[1, 1],
#       [0, 1]])
my_spiral_ones(2)

In [ ]:
# Output:
#array([[0, 1, 1],
#       [0, 0, 1],
#       [1, 1, 1]])
my_spiral_ones(3)

In [ ]:
# Output:
#array([[1, 0, 0, 0],
#       [1, 0, 1, 1],
#       [1, 0, 0, 1],
#       [1, 1, 1, 1]])
my_spiral_ones(4)

In [ ]:
# Output:
#array([[1, 1, 1, 1, 1],
#       [1, 0, 0, 0, 0],
#       [1, 0, 1, 1, 0],
#       [1, 0, 0, 1, 0],
#       [1, 1, 1, 1, 0]])
my_spiral_ones(5)

10. Réécrivez *my_spiral_ones* sans utiliser la récursivité.
11. Dessinez l'arbre de récursivité pour *my_towers(4)*.
12. Réécrivez la fonction Tours de Hanoï dans ce chapitre sans utiliser la récursivité.
13. Dessinez l'arbre de récursivité pour *my_quicksort([5 4 6 2 9 1 7 3])*.
14. Réécrivez la fonction *quicksort* dans ce chapitre sans utiliser la récursivité.

<!--NAVIGATION-->
< [6.2 Divide and Conquer](chapter06.02-Divide-and-Conquer.ipynb) | [Contents](Index.ipynb) | [7.0 Objects and Classes](chapter07.00-Objects-and-Classes.ipynb) >