<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*Ce cahier contient un extrait de [Programmation Python et méthodes numériques - Un guide pour les ingénieurs et les scientifiques](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html), le contenu est également disponible sur [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*Les droits d'auteur du livre appartiennent à Elsevier. Nous avons également ce livre interactif en ligne pour une meilleure expérience d'apprentissage. Le code est publié sous la [licence MIT](https://opensource.org/licenses/MIT). Si vous trouvez ce contenu utile, pensez à soutenir le travail sur [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) ou [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1) !*

<!--NAVIGATION-->
< [14.4 Solutions to Systems of Linear Equations](chapter14.04-Solutions-to-Systems-of-Linear-Equations.ipynb)  | [Contents](Index.ipynb) | [14.6 Matrix Inversion](chapter14.06-Matrix-Inversion.ipynb) >

# Résoudre des systèmes d'équations linéaires en Python

Bien que nous ayons discuté de diverses méthodes pour résoudre les systèmes d’équations linéaires, il est en fait très simple de le faire en Python. Dans cette section, nous utiliserons Python pour résoudre les systèmes d’équations. Le moyen le plus simple d'obtenir une solution consiste à utiliser la fonction *solve* dans Numpy.

**ESSAYEZ-LE !** Utilisez numpy.linalg.solve pour résoudre les équations suivantes.

\begin{eqnarray*}
4x_1 + 3x_2 - 5x_3 &=& 2 \\
-2x_1 - 4x_2 + 5x_3 &=& 5 \\
8x_1 + 8x_2  &=& -3 \\
\end{eqnarray*}

In [1]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


Nous pouvons voir que nous obtenons les mêmes résultats que dans la section précédente lorsque nous avons calculé manuellement. Sous le capot, le solveur effectue en fait une décomposition LU pour obtenir les résultats. Vous pouvez vérifier l'aide de la fonction, elle a besoin que la matrice d'entrée soit carrée et de rang complet, c'est-à-dire que toutes les lignes (ou, de manière équivalente, les colonnes) doivent être linéairement indépendantes.

**ESSAYEZ-LE !** Essayez de résoudre les équations ci-dessus en utilisant l'approche d'inversion matricielle.

In [2]:
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


Nous pouvons également obtenir les matrices $L$ et $U$ utilisées dans la décomposition LU en utilisant le package scipy.

**ESSAYEZ-LE !** Obtenez les $L$ et $U$ pour la matrice A ci-dessus.

In [3]:
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


Nous pouvons voir que les $L$ et $U$ que nous obtenons sont différents de ceux que nous avons obtenus manuellement dans la dernière section. Vous verrez également qu'il existe une **matrice de permutation** $P$ renvoyée par la fonction *lu*. Cette matrice de permutation enregistre comment modifier l'ordre des équations pour faciliter les calculs (par exemple, si le premier élément de la première ligne est zéro, il ne peut pas s'agir de l'équation pivot, car vous ne pouvez pas transformer les premiers éléments des autres lignes en zéro. Par conséquent, nous devons changer l’ordre des équations pour obtenir une nouvelle équation pivot). Si vous multipliez $P$ par $A$, vous verrez que cette matrice de permutation inverse l'ordre des équations dans ce cas.

**ESSAYEZ-LE !** Multipliez $P$ et $A$ et voyez quel est l'effet de la matrice de permutation sur $A$.

In [4]:
print(np.dot(P, A))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


<!--NAVIGATION-->
< [14.4 Solutions to Systems of Linear Equations](chapter14.04-Solutions-to-Systems-of-Linear-Equations.ipynb)  | [Contents](Index.ipynb) | [14.6 Matrix Inversion](chapter14.06-Matrix-Inversion.ipynb) >